on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip3 install --user -r requirements_test.txt

      - name: Check formatting
        run: |
          black .
          git diff --exit-code

      - name: Run test suite
        run: |
          coverage run -m pytest test_concurrently.py
          coverage report
